// src/views/practice/ReadingPracticeView.vue
<template>
  <div>
    <h1 class="text-h4 mb-1">Reading Practice</h1>
    <p class="text-medium-emphasis mb-4">
      2026 adaptive format: Stage 1 (15 questions) → Stage 2 Easy or Hard based on your score.
    </p>

    <SectionTimer label="Reading Section Timer" :time="timer.formatted" :percent="timer.percent" />

    <!-- Question navigation chips -->
    <div class="mb-3 d-flex ga-1 flex-wrap">
      <v-chip
        v-for="(item, i) in currentSet"
        :key="item.id"
        :color="i === idx ? 'primary' : answered[i] ? 'success' : undefined"
        size="x-small"
        @click="jump(i)"
      >
        Q{{ i + 1 }}
      </v-chip>
    </div>

    <!-- Stage indicator -->
    <div class="mb-3 d-flex ga-2 align-center">
      <v-chip size="small" :color="stage2Mode !== 'pending' ? (stage2Mode === 'hard' ? 'error' : 'info') : 'default'" variant="tonal">
        {{ stage2Mode === 'pending' ? 'Stage 1 — Foundation' : stage2Mode === 'hard' ? 'Stage 2 — Hard (Academic)' : 'Stage 2 — Easy (Daily Life)' }}
      </v-chip>
      <span v-if="stage2Mode !== 'pending'" class="text-caption text-medium-emphasis">
        Stage 1 score: {{ stage1Score }}/{{ readingAdaptive.stage1.length }}
      </span>
    </div>

    <!-- Results banner -->
    <v-alert v-if="finished" type="success" variant="tonal" class="mb-4">
      <div class="d-flex flex-wrap ga-4 align-center">
        <div>Score: <strong>{{ score }}/{{ currentSet.length }}</strong> ({{ percent }}%)</div>
        <div>Estimated Band: <strong>{{ band }}</strong></div>
        <div>Stage 2 taken: <strong>{{ stage2Mode }}</strong></div>
      </div>
    </v-alert>

    <!-- Question card -->
    <v-card v-if="!finished" rounded="xl" elevation="0" class="pa-5">
      <div class="d-flex justify-space-between align-center mb-1">
        <div class="text-overline">Question {{ idx + 1 }} / {{ currentSet.length }}</div>
        <div class="text-caption text-medium-emphasis">{{ q.type }}</div>
      </div>

      <!-- ── Complete the Words — text-fill ──────────────────── -->
      <template v-if="q.type === 'Complete the Words'">
        <div class="text-caption text-medium-emphasis mb-2">
          Read the passage. Each truncated word (e.g. <code>inves___</code>) has a blank.
          Type the complete word in the field below it.
        </div>

        <div
          class="mb-4 pa-3 rounded text-body-1"
          style="background: rgba(0,0,0,0.04); border-left: 3px solid rgba(var(--v-theme-primary), 0.4); line-height: 1.9"
        >
          {{ q.passageText }}
        </div>

        <div class="mb-4">
          <div
            v-for="(blank, bi) in q.blanks"
            :key="bi"
            class="d-flex align-center ga-3 mb-3"
          >
            <v-chip size="small" color="primary" variant="tonal" class="flex-shrink-0">
              {{ blank.incomplete }}
            </v-chip>
            <v-text-field
              v-model="ctwAnswers[bi]"
              :label="`Complete word ${bi + 1}`"
              variant="outlined"
              density="compact"
              hide-details
              style="max-width: 220px"
              @keyup.enter="submitAnswer"
            />
            <v-icon
              v-if="answered[idx]"
              :color="ctwAnswers[bi]?.toLowerCase().trim() === blank.answer.toLowerCase() ? 'success' : 'error'"
              size="small"
            >
              {{ ctwAnswers[bi]?.toLowerCase().trim() === blank.answer.toLowerCase() ? 'mdi-check-circle' : 'mdi-close-circle' }}
            </v-icon>
          </div>
        </div>

        <v-alert
          v-if="answered[idx]"
          :type="responses[idx] === 1 ? 'success' : 'error'"
          variant="tonal"
          density="compact"
          class="mb-3"
        >
          <span v-if="responses[idx] === 1">All blanks correct!</span>
          <span v-else>
            Correct answers:
            <strong>{{ q.blanks.map(b => b.answer).join(', ') }}</strong>
          </span>
        </v-alert>

        <v-btn
          color="primary"
          :disabled="!ctwAllFilled"
          @click="submitAnswer"
        >
          {{ idx === currentSet.length - 1 ? 'Finish Section' : 'Next' }}
        </v-btn>
      </template>

      <!-- ── MCQ (Daily Life / Academic Passage) ──────────────── -->
      <template v-else>
        <div
          v-if="q.passage"
          class="mb-4 pa-3 rounded text-body-2"
          style="background: rgba(0,0,0,0.04); border-left: 3px solid rgba(var(--v-theme-primary), 0.4)"
        >
          {{ q.passage }}
        </div>

        <p class="font-weight-medium mb-4 text-body-1">{{ q.prompt }}</p>

        <v-radio-group v-model="selected" class="mb-4">
          <v-radio v-for="(opt, i) in q.options" :key="i" :label="opt" :value="i" class="mb-1" />
        </v-radio-group>

        <v-btn color="primary" :disabled="selected === null" @click="submitAnswer">
          {{ idx === currentSet.length - 1 ? 'Finish Section' : 'Next' }}
        </v-btn>
      </template>
    </v-card>

    <!-- Review card -->
    <v-card v-if="finished" rounded="xl" elevation="0" class="pa-4 mt-3">
      <div class="text-h6 mb-3">Question Review</div>
      <v-expansion-panels>
        <v-expansion-panel v-for="(item, i) in currentSet" :key="item.id">
          <v-expansion-panel-title>
            <div class="d-flex ga-2 align-center">
              <v-icon
                :color="responses[i] === 1 || (item.answer !== undefined && responses[i] === item.answer) ? 'success' : 'error'"
                size="small"
              >
                {{ responses[i] === 1 || (item.answer !== undefined && responses[i] === item.answer) ? 'mdi-check-circle' : 'mdi-close-circle' }}
              </v-icon>
              Q{{ i + 1 }} · {{ item.type }}
            </div>
          </v-expansion-panel-title>
          <v-expansion-panel-text>
            <!-- CTW review -->
            <template v-if="item.type === 'Complete the Words'">
              <div
                class="mb-2 pa-2 rounded text-body-2 text-medium-emphasis"
                style="background: rgba(0,0,0,0.04)"
              >
                {{ item.passageText }}
              </div>
              <div v-for="(b, bi) in item.blanks" :key="bi" class="mb-1 text-body-2">
                <span class="text-medium-emphasis">{{ b.incomplete }}</span>
                → Correct: <strong class="text-success">{{ b.answer }}</strong>
              </div>
            </template>
            <!-- MCQ review -->
            <template v-else>
              <div
                v-if="item.passage"
                class="mb-2 pa-2 rounded text-body-2 text-medium-emphasis"
                style="background: rgba(0,0,0,0.04)"
              >
                {{ item.passage }}
              </div>
              <div class="mb-2">{{ item.prompt }}</div>
              <div class="mb-1">
                Your answer:
                <strong :class="responses[i] === item.answer ? 'text-success' : 'text-error'">
                  {{ item.options?.[responses[i]] ?? 'Not answered' }}
                </strong>
              </div>
              <div>
                Correct answer: <strong class="text-success">{{ item.options?.[item.answer] }}</strong>
              </div>
            </template>
          </v-expansion-panel-text>
        </v-expansion-panel>
      </v-expansion-panels>
    </v-card>

    <v-btn class="mt-4" variant="text" @click="restart">↺ Restart</v-btn>
  </div>
</template>

<script setup>
import { computed, ref, watch, onMounted } from 'vue'
import { readingAdaptive } from '../../data/reading'
import { useProgressStore } from '../../stores/progress'
import { useTimer } from '../../composables/useTimer'
import { useBandEstimate } from '../../composables/useBandEstimate'
import SectionTimer from '../../components/SectionTimer.vue'

const progress = useProgressStore()
const TOTAL_TIME = 30 * 60 // 30 minutes for full adaptive session

const timer = useTimer(TOTAL_TIME)

const stage2Mode = ref('pending')
const stage1Score = ref(0)
const pool = ref([...readingAdaptive.stage1])
const idx = ref(0)
const selected = ref(null)
const ctwAnswers = ref([])
const score = ref(0)
const finished = ref(false)
const answered = ref({})
const responses = ref({})

const q = computed(() => pool.value[idx.value])
const currentSet = computed(() => pool.value)
const percent = computed(() =>
  currentSet.value.length ? Math.round((score.value / currentSet.value.length) * 100) : 0
)
const band = computed(() => useBandEstimate(percent.value))

const isCTW = computed(() => q.value?.type === 'Complete the Words')
const ctwAllFilled = computed(() =>
  isCTW.value && q.value.blanks
    ? q.value.blanks.every((_, i) => ctwAnswers.value[i]?.trim())
    : false
)

// Reset CTW answers when question changes
watch(idx, () => {
  if (isCTW.value && q.value.blanks) {
    ctwAnswers.value = new Array(q.value.blanks.length).fill('')
  } else {
    ctwAnswers.value = []
  }
  selected.value = responses.value[idx.value] ?? null
})

const finalize = () => {
  if (finished.value) return
  finished.value = true
  timer.stop()
  progress.addReading(percent.value, {
    stage2Mode: stage2Mode.value,
    score: score.value,
    total: currentSet.value.length,
    percent: percent.value,
    band: band.value,
    responses: responses.value,
  })
}

const jump = (i) => {
  idx.value = i
  selected.value = responses.value[i] ?? null
}

const submitAnswer = () => {
  const item = q.value
  let correct = 0

  if (item.type === 'Complete the Words') {
    if (!ctwAllFilled.value) return
    const allCorrect = item.blanks.every(
      (b, i) => ctwAnswers.value[i]?.toLowerCase().trim() === b.answer.toLowerCase()
    )
    correct = allCorrect ? 1 : 0
    // Store 1 or 0 (so review icon works: responses[i] === 1 means correct)
  } else {
    if (selected.value === null) return
    correct = selected.value === item.answer ? 1 : 0
  }

  // Undo previous score contribution for this question if re-answering
  const prev = responses.value[idx.value]
  if (prev !== undefined) {
    if (prev === 1 && item.type === 'Complete the Words') score.value -= 1
    else if (prev === item.answer && item.type !== 'Complete the Words') score.value -= 1
  }

  answered.value[idx.value] = true
  if (item.type === 'Complete the Words') {
    responses.value[idx.value] = correct // 1 or 0
  } else {
    responses.value[idx.value] = selected.value
  }
  score.value += correct

  // Still in stage 1 and questions remain
  if (idx.value < pool.value.length - 1) {
    idx.value += 1
    return
  }

  // End of current pool — check if we need to add stage 2
  if (stage2Mode.value === 'pending') {
    stage1Score.value = score.value
    const threshold = Math.ceil(readingAdaptive.stage1.length * 0.5)
    stage2Mode.value = score.value >= threshold ? 'hard' : 'easy'
    pool.value = [
      ...pool.value,
      ...(stage2Mode.value === 'hard' ? readingAdaptive.stage2Hard : readingAdaptive.stage2Easy),
    ]
    idx.value += 1
    selected.value = null
    ctwAnswers.value = []
    return
  }

  // All done
  finalize()
}

const restart = () => {
  stage2Mode.value = 'pending'
  stage1Score.value = 0
  pool.value = [...readingAdaptive.stage1]
  idx.value = 0
  score.value = 0
  selected.value = null
  ctwAnswers.value = []
  finished.value = false
  answered.value = {}
  responses.value = {}
  timer.reset(TOTAL_TIME)
  timer.start(finalize)
}

onMounted(restart)
</script>

// src/views/practice/ReadingPracticeView.jsx
import React, { useEffect, useRef, useState } from 'react'
import {
  Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Card,
  CardContent, Chip, Dialog, DialogActions, DialogContent, DialogContentText,
  DialogTitle, FormControl, FormControlLabel, Radio, RadioGroup, TextField, Typography,
} from '@mui/material'
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'
import CheckCircleIcon from '@mui/icons-material/CheckCircle'
import CancelIcon from '@mui/icons-material/Cancel'
import { readingAdaptive } from '../../data/reading'
import { useProgressStore } from '../../store/useProgressStore'
import { useAuthStore } from '../../store/useAuthStore'
import { useTimer } from '../../hooks/useTimer'
import { getBandEstimate } from '../../hooks/useBandEstimate'
import SectionTimer from '../../components/SectionTimer'
import { supabase } from '../../lib/supabase'

const TOTAL_TIME = 30 * 60

// Returns the display form of a CTW blank with one underscore per missing character.
// e.g. toSpacedDisplay('inves___', 'investigate') → 'inves_ _ _ _ _ _'
function toSpacedDisplay(incomplete, answer) {
  const prefix = incomplete.replace(/_{2,}$/, '')
  const missingCount = answer.length - prefix.length
  if (missingCount <= 0) return prefix
  return prefix + Array(missingCount).fill('_').join(' ')
}

function formatPassageText(passageText, blanks) {
  let text = passageText
  blanks.forEach((blank) => {
    text = text.replace(blank.incomplete, toSpacedDisplay(blank.incomplete, blank.answer))
  })
  return text
}

export default function ReadingPracticeView() {
  const progress = useProgressStore()
  const userId = useAuthStore((s) => s.user?.id)
  const timer = useTimer(TOTAL_TIME)

  const [stage2Mode, setStage2Mode] = useState('pending')
  const [stage1Score, setStage1Score] = useState(0)
  const [pool, setPool] = useState([...readingAdaptive.stage1])
  const [idx, setIdx] = useState(0)
  const [selected, setSelected] = useState(null)
  const [ctwAnswers, setCtwAnswers] = useState([])
  const [score, setScore] = useState(0)
  const [finished, setFinished] = useState(false)
  const [answered, setAnswered] = useState({})
  const [responses, setResponses] = useState({})
  const [showFeedback, setShowFeedback] = useState(false)
  const [lastResult, setLastResult] = useState(null) // { correct, correctAnswer, yourAnswer }
  const [resumeDialog, setResumeDialog] = useState(false)
  const [pendingResume, setPendingResume] = useState(null)

  // Supabase session helpers
  const upsertSession = (data) => {
    if (!userId) return
    supabase.from('reading_sessions').upsert(
      { user_id: userId, session_data: data, updated_at: new Date().toISOString() },
      { onConflict: 'user_id' }
    )
  }
  const deleteSession = () => {
    if (!userId) return
    supabase.from('reading_sessions').delete().eq('user_id', userId)
  }

  // Refs for latest state in timer callback
  const stateRef = useRef({})
  stateRef.current = { pool, score, stage2Mode, responses }

  const q = pool[idx]
  const isCTW = q?.type === 'Complete the Words'
  const ctwAllFilled = isCTW && q?.blanks
    ? q.blanks.every((_, i) => ctwAnswers[i]?.trim())
    : false

  // Progress saving when finished state changes
  useEffect(() => {
    if (!finished) return
    const { pool: p, score: sc, stage2Mode: sm, responses: res } = stateRef.current
    const pct = p.length ? Math.round((sc / p.length) * 100) : 0
    progress.addReading(pct, {
      stage2Mode: sm,
      score: sc,
      total: p.length,
      percent: pct,
      band: getBandEstimate(pct),
      responses: res,
    }, userId)
  }, [finished]) // eslint-disable-line

  const finalize = () => {
    deleteSession()
    setFinished(true)
    timer.stop()
  }

  // Stable wrapper for timer so it always calls latest finalize
  const finalizeRef = useRef(finalize)
  finalizeRef.current = finalize

  const restart = () => {
    setStage2Mode('pending')
    setStage1Score(0)
    setPool([...readingAdaptive.stage1])
    setIdx(0)
    setScore(0)
    setSelected(null)
    setCtwAnswers([])
    setFinished(false)
    setAnswered({})
    setResponses({})
    setShowFeedback(false)
    setLastResult(null)
    setResumeDialog(false)
    setPendingResume(null)
    deleteSession()
    timer.reset(TOTAL_TIME)
    timer.start(() => finalizeRef.current())
  }

  useEffect(() => { restart() }, []) // eslint-disable-line

  // Check Supabase for a saved in-progress session when user logs in
  useEffect(() => {
    if (!userId) return
    supabase
      .from('reading_sessions')
      .select('session_data')
      .eq('user_id', userId)
      .single()
      .then(({ data, error }) => {
        if (!error && data?.session_data) {
          setPendingResume(data.session_data)
          setResumeDialog(true)
        }
      })
  }, [userId]) // eslint-disable-line

  const applyResume = () => {
    const d = pendingResume
    let restoredPool
    if (d.stage2Mode === 'pending') restoredPool = [...readingAdaptive.stage1]
    else if (d.stage2Mode === 'hard') restoredPool = [...readingAdaptive.stage1, ...readingAdaptive.stage2Hard]
    else restoredPool = [...readingAdaptive.stage1, ...readingAdaptive.stage2Easy]

    setPool(restoredPool)
    setIdx(d.idx)
    setScore(d.score)
    setStage2Mode(d.stage2Mode)
    setStage1Score(d.stage1Score)
    setResponses(d.responses)
    setAnswered(d.answered)
    setSelected(d.responses[d.idx] ?? null)
    setShowFeedback(false)
    setLastResult(null)
    setFinished(false)
    setResumeDialog(false)
    setPendingResume(null)
    timer.reset(TOTAL_TIME)
    timer.start(() => finalizeRef.current())
  }

  // Reset CTW/selection when question changes
  useEffect(() => {
    if (isCTW && q?.blanks) {
      setCtwAnswers(new Array(q.blanks.length).fill(''))
    } else {
      setCtwAnswers([])
    }
    setSelected(responses[idx] ?? null)
  }, [idx]) // eslint-disable-line

  const jump = (i) => {
    setIdx(i)
    setSelected(responses[i] ?? null)
    setShowFeedback(false)
    setLastResult(null)
  }

  const submitAnswer = () => {
    const item = q
    let correct = 0
    if (item.type === 'Complete the Words') {
      if (!ctwAllFilled) return
      correct = item.blanks.every((b, i) => ctwAnswers[i]?.toLowerCase().trim() === b.answer.toLowerCase()) ? 1 : 0
    } else {
      if (selected === null) return
      correct = selected === item.answer ? 1 : 0
    }

    const prev = responses[idx]
    let scoreDelta = correct
    if (prev !== undefined) {
      if (prev === 1 && item.type === 'Complete the Words') scoreDelta -= 1
      else if (prev === item.answer && item.type !== 'Complete the Words') scoreDelta -= 1
    }

    const newScore = score + scoreDelta
    const newResponses = { ...responses, [idx]: item.type === 'Complete the Words' ? correct : selected }
    const newAnswered = { ...answered, [idx]: true }

    setAnswered(newAnswered)
    setResponses(newResponses)
    setScore(newScore)

    // Persist to Supabase so session survives browser/device changes
    upsertSession({
      idx,
      score: newScore,
      stage2Mode,
      stage1Score,
      responses: newResponses,
      answered: newAnswered,
    })

    // Build feedback info
    if (item.type === 'Complete the Words') {
      setLastResult({
        correct: correct === 1,
        isCTW: true,
        blanks: item.blanks,
        userAnswers: [...ctwAnswers],
      })
    } else {
      setLastResult({
        correct: correct === 1,
        isCTW: false,
        correctAnswer: item.options?.[item.answer],
        yourAnswer: item.options?.[selected],
      })
    }
    setShowFeedback(true)

    // Stash advance info for when user clicks Continue
    pendingAdvanceRef.current = { newScore, newResponses, newAnswered }
  }

  const pendingAdvanceRef = useRef(null)

  const advance = () => {
    const { newScore, newAnswered } = pendingAdvanceRef.current ?? {}
    setShowFeedback(false)
    setLastResult(null)

    if (idx < pool.length - 1) {
      const nextIdx = idx + 1
      setIdx(nextIdx)
      setSelected(null)
      setCtwAnswers([])
      upsertSession({ idx: nextIdx, score: newScore, stage2Mode, stage1Score, responses, answered })
      return
    }

    if (stage2Mode === 'pending') {
      const threshold = Math.ceil(readingAdaptive.stage1.length * 0.5)
      const newMode = newScore >= threshold ? 'hard' : 'easy'
      const nextIdx = idx + 1
      setStage1Score(newScore)
      setStage2Mode(newMode)
      setPool((prev) => [
        ...prev,
        ...(newMode === 'hard' ? readingAdaptive.stage2Hard : readingAdaptive.stage2Easy),
      ])
      setIdx(nextIdx)
      setSelected(null)
      setCtwAnswers([])
      upsertSession({ idx: nextIdx, score: newScore, stage2Mode: newMode, stage1Score: newScore, responses, answered })
      return
    }

    finalize()
  }

  const pct = pool.length ? Math.round((score / pool.length) * 100) : 0
  const band = getBandEstimate(pct)

  return (
    <Box>
      <Typography variant="h4" gutterBottom>Reading Practice</Typography>
      <Typography color="text.secondary" sx={{ mb: 3 }}>
        2026 adaptive format: Stage 1 (15 questions) → Stage 2 Easy or Hard based on your score.
      </Typography>

      <SectionTimer label="Reading Section Timer" time={timer.formatted} percent={timer.percent} />

      {/* Question nav chips */}
      <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap', mb: 2 }}>
        {pool.map((item, i) => (
          <Chip
            key={item.id}
            label={`Q${i + 1}`}
            size="small"
            color={i === idx ? 'primary' : answered[i] ? 'success' : 'default'}
            onClick={() => jump(i)}
            sx={{ cursor: 'pointer' }}
          />
        ))}
      </Box>

      {/* Stage indicator */}
      <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', mb: 2 }}>
        <Chip
          size="small"
          label={
            stage2Mode === 'pending' ? 'Stage 1 — Foundation'
              : stage2Mode === 'hard' ? 'Stage 2 — Hard (Academic)' : 'Stage 2 — Easy (Daily Life)'
          }
          color={stage2Mode === 'pending' ? 'default' : stage2Mode === 'hard' ? 'error' : 'info'}
          variant="outlined"
        />
        {stage2Mode !== 'pending' && (
          <Typography variant="caption" color="text.secondary">
            Stage 1 score: {stage1Score}/{readingAdaptive.stage1.length}
          </Typography>
        )}
      </Box>

      {finished && (
        <Alert severity="success" sx={{ mb: 2 }}>
          Score: <strong>{score}/{pool.length}</strong> ({pct}%) · Estimated Band: <strong>{band}</strong> · Stage 2: <strong>{stage2Mode}</strong>
        </Alert>
      )}

      {/* Question card */}
      {!finished && q && (
        <Card elevation={0} sx={{ borderRadius: 3, mb: 2 }}>
          <CardContent>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
              <Typography variant="overline">Question {idx + 1} / {pool.length}</Typography>
              <Typography variant="caption" color="text.secondary">{q.type}</Typography>
            </Box>

            {(() => {
              // Show feedback if just submitted OR jumping back to an already-answered question
              const displayFeedback = showFeedback || !!answered[idx]
              const storedResponse = responses[idx]
              const ctwCorrect = storedResponse === 1
              const mcqCorrect = storedResponse === q?.answer

              return isCTW ? (
                <>
                  <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 1 }}>
                    Read the passage. Each _ represents one missing letter (e.g. <code>inves_ _ _ _ _ _</code> = <em>investigate</em>). Type the complete word.
                  </Typography>
                  <Box sx={{ mb: 3, p: 2, borderRadius: 2, borderLeft: '3px solid', borderColor: 'primary.main', bgcolor: 'action.hover', lineHeight: 1.9 }}>
                    <Typography variant="body1">{formatPassageText(q.passageText, q.blanks ?? [])}</Typography>
                  </Box>
                  <Box sx={{ mb: 3 }}>
                    {q.blanks?.map((blank, bi) => (
                      <Box key={bi} sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 2 }}>
                        <Chip label={toSpacedDisplay(blank.incomplete, blank.answer)} size="small" color="primary" variant="outlined" sx={{ flexShrink: 0 }} />
                        <TextField
                          value={ctwAnswers[bi] || ''}
                          onChange={(e) => {
                            const next = [...ctwAnswers]
                            next[bi] = e.target.value
                            setCtwAnswers(next)
                          }}
                          label={`Complete word ${bi + 1}`}
                          size="small"
                          sx={{ maxWidth: 220 }}
                          disabled={displayFeedback}
                          onKeyDown={(e) => { if (e.key === 'Enter' && ctwAllFilled && !displayFeedback) submitAnswer() }}
                        />
                        {/* Per-blank icons only available on fresh submit (lastResult has userAnswers) */}
                        {showFeedback && lastResult?.isCTW && (
                          lastResult.userAnswers[bi]?.toLowerCase().trim() === blank.answer.toLowerCase()
                            ? <CheckCircleIcon color="success" fontSize="small" />
                            : <CancelIcon color="error" fontSize="small" />
                        )}
                      </Box>
                    ))}
                  </Box>
                  {displayFeedback && (
                    <Alert severity={ctwCorrect ? 'success' : 'error'} sx={{ mb: 2 }}>
                      {ctwCorrect
                        ? 'All blanks correct!'
                        : <>Incorrect. Correct answers: <strong>{q.blanks?.map((b) => b.answer).join(', ')}</strong></>}
                    </Alert>
                  )}
                  {!displayFeedback ? (
                    <Button variant="contained" disabled={!ctwAllFilled} onClick={submitAnswer}>Submit</Button>
                  ) : showFeedback ? (
                    <Button variant="contained" onClick={advance}>
                      {idx === pool.length - 1 ? 'Finish Section' : 'Continue →'}
                    </Button>
                  ) : idx < pool.length - 1 ? (
                    <Button variant="outlined" onClick={() => setIdx(idx + 1)}>Next →</Button>
                  ) : null}
                </>
              ) : (
                <>
                  {q.passage && (
                    <Box sx={{ mb: 3, p: 2, borderRadius: 2, borderLeft: '3px solid', borderColor: 'primary.main', bgcolor: 'action.hover' }}>
                      <Typography variant="body2">{q.passage}</Typography>
                    </Box>
                  )}
                  <Typography fontWeight={500} sx={{ mb: 3 }}>{q.prompt}</Typography>
                  <FormControl>
                    <RadioGroup
                      value={selected ?? ''}
                      onChange={(e) => { if (!displayFeedback) setSelected(Number(e.target.value)) }}
                    >
                      {q.options?.map((opt, i) => (
                        <FormControlLabel
                          key={i}
                          value={i}
                          control={<Radio />}
                          label={
                            displayFeedback ? (
                              <Box component="span" sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                                {opt}
                                {i === q.answer && <CheckCircleIcon color="success" fontSize="small" />}
                                {i === storedResponse && i !== q.answer && <CancelIcon color="error" fontSize="small" />}
                              </Box>
                            ) : opt
                          }
                          sx={{ mb: 0.5 }}
                          disabled={displayFeedback}
                        />
                      ))}
                    </RadioGroup>
                  </FormControl>
                  {displayFeedback && (
                    <Alert severity={mcqCorrect ? 'success' : 'error'} sx={{ mt: 2, mb: 1 }}>
                      {mcqCorrect
                        ? 'Correct!'
                        : <>Incorrect. Correct answer: <strong>{q.options?.[q.answer]}</strong></>}
                    </Alert>
                  )}
                  <Box sx={{ mt: 2 }}>
                    {!displayFeedback ? (
                      <Button variant="contained" disabled={selected === null} onClick={submitAnswer}>Submit</Button>
                    ) : showFeedback ? (
                      <Button variant="contained" onClick={advance}>
                        {idx === pool.length - 1 ? 'Finish Section' : 'Continue →'}
                      </Button>
                    ) : idx < pool.length - 1 ? (
                      <Button variant="outlined" onClick={() => setIdx(idx + 1)}>Next →</Button>
                    ) : null}
                  </Box>
                </>
              )
            })()}
          </CardContent>
        </Card>
      )}

      {/* Review */}
      {finished && (
        <Card elevation={0} sx={{ borderRadius: 3, mb: 2 }}>
          <CardContent>
            <Typography variant="h6" gutterBottom>Question Review</Typography>
            {pool.map((item, i) => {
              const isCorrect = item.type === 'Complete the Words'
                ? responses[i] === 1
                : responses[i] === item.answer
              return (
                <Accordion key={item.id} elevation={0} sx={{ mb: 0.5 }}>
                  <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                      {isCorrect
                        ? <CheckCircleIcon color="success" fontSize="small" />
                        : <CancelIcon color="error" fontSize="small" />}
                      <Typography variant="body2">Q{i + 1} · {item.type}</Typography>
                    </Box>
                  </AccordionSummary>
                  <AccordionDetails>
                    {item.type === 'Complete the Words' ? (
                      <>
                        <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>{item.passageText}</Typography>
                        {item.blanks?.map((b, bi) => (
                          <Typography key={bi} variant="body2" sx={{ mb: 0.5 }}>
                            {toSpacedDisplay(b.incomplete, b.answer)} → Correct: <strong style={{ color: '#4caf50' }}>{b.answer}</strong>
                          </Typography>
                        ))}
                      </>
                    ) : (
                      <>
                        {item.passage && (
                          <Box sx={{ mb: 1, p: 1, borderRadius: 1, bgcolor: 'action.hover' }}>
                            <Typography variant="body2" color="text.secondary">{item.passage}</Typography>
                          </Box>
                        )}
                        <Typography variant="body2" sx={{ mb: 1 }}>{item.prompt}</Typography>
                        <Typography variant="body2" sx={{ mb: 0.5 }}>
                          Your answer:{' '}
                          <strong style={{ color: responses[i] === item.answer ? '#4caf50' : '#f44336' }}>
                            {item.options?.[responses[i]] ?? 'Not answered'}
                          </strong>
                        </Typography>
                        <Typography variant="body2">
                          Correct: <strong style={{ color: '#4caf50' }}>{item.options?.[item.answer]}</strong>
                        </Typography>
                      </>
                    )}
                  </AccordionDetails>
                </Accordion>
              )
            })}
          </CardContent>
        </Card>
      )}

      <Button variant="text" onClick={restart}>↺ Restart</Button>

      {/* Resume session dialog */}
      <Dialog open={resumeDialog} onClose={() => { setResumeDialog(false); setPendingResume(null) }}>
        <DialogTitle>Resume previous session?</DialogTitle>
        <DialogContent>
          <DialogContentText>
            You have an unfinished reading session at question{' '}
            <strong>{pendingResume ? pendingResume.idx + 1 : ''}</strong>.
            Would you like to continue where you left off?
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setResumeDialog(false); setPendingResume(null); deleteSession() }}>
            Start Fresh
          </Button>
          <Button variant="contained" onClick={applyResume}>Resume</Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
