// src/views/practice/WritingPracticeView.jsx
import React, { useEffect, useRef, useState, useMemo } from 'react'
import {
  Alert, Box, Button, Card, CardContent, Chip, Snackbar, TextField, Typography,
} from '@mui/material'
import { writingTasks } from '../../data/writing'
import { useTimer } from '../../hooks/useTimer'
import SectionTimer from '../../components/SectionTimer'
import { useProgressStore } from '../../store/useProgressStore'

const taskTypes = ['all', 'Build a Sentence', 'Write an Email', 'Academic Discussion']

const taskTypeColor = (type) => {
  if (type === 'Build a Sentence') return 'success'
  if (type === 'Write an Email') return 'primary'
  return 'secondary'
}

const formatTime = (sec) => {
  const m = Math.floor(sec / 60)
  const s = sec % 60
  return s === 0 ? `${m} min` : `${m}:${String(s).padStart(2, '0')}`
}

export default function WritingPracticeView() {
  const progress = useProgressStore()
  const [filterType, setFilterType] = useState('all')
  const [currentIndex, setCurrentIndex] = useState(0)
  const [response, setResponse] = useState('')
  const [submitted, setSubmitted] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [toast, setToast] = useState(false)
  const [showSample, setShowSample] = useState(false)
  const [completedIds, setCompletedIds] = useState(new Set())
  const [arrangedChunks, setArrangedChunks] = useState([])

  const filteredTasks = useMemo(
    () => (filterType === 'all' ? writingTasks : writingTasks.filter((t) => t.type === filterType)),
    [filterType]
  )

  const task = filteredTasks[currentIndex] || writingTasks[0]
  const timer = useTimer(task.time)

  const shuffledChunks = useMemo(() => {
    if (task.type !== 'Build a Sentence' || !task.chunks) return []
    const seed = task.id.charCodeAt(task.id.length - 1)
    return [...task.chunks].sort(
      (a, b) => (a.charCodeAt(0) * seed + a.length) % 11 - (b.charCodeAt(0) * seed + b.length) % 11
    )
  }, [task.id, task.type, task.chunks])

  const availableChunks = shuffledChunks.filter((c) => !arrangedChunks.includes(c))
  const chunkArrangementCorrect = task.type === 'Build a Sentence' && task.chunks
    ? arrangedChunks.join(' ') === task.chunks.join(' ')
    : false

  const words = response.trim() ? response.trim().split(/\s+/).length : 0
  const quality = (() => {
    const lengthScore = Math.max(1, Math.min(5, Math.round((words / (task.minWords || 80)) * 5)))
    const sentenceCount = response.split(/[.!?]+/).filter(Boolean).length
    const structureScore = Math.max(1, Math.min(5, sentenceCount >= 4 ? 5 : sentenceCount + 1))
    return Math.round((lengthScore + structureScore) / 2)
  })()

  const canSubmit = (() => {
    if (submitting || submitted) return false
    if (task.type === 'Build a Sentence') return task.chunks && arrangedChunks.length === task.chunks.length
    return response.trim().length > 0
  })()

  const resetTaskState = () => {
    setResponse('')
    setArrangedChunks([])
    setSubmitted(false)
    setSubmitting(false)
    setShowSample(false)
  }

  // Timer restart ref pattern
  const submitRef = useRef(null)
  const restartTimerRef = useRef(null)

  const submit = async () => {
    if (!canSubmit) return
    setSubmitting(true)
    if (task.type === 'Build a Sentence') setResponse(arrangedChunks.join(' '))
    await new Promise((r) => setTimeout(r, 200))
    setSubmitted(true)
    setSubmitting(false)
    setToast(true)
    setCompletedIds((s) => new Set([...s, task.id]))
    progress.addWriting()
  }
  submitRef.current = submit

  const restartTimer = () => {
    timer.reset(task.time)
    timer.start(() => { if (!submitted) submitRef.current?.() })
  }
  restartTimerRef.current = restartTimer

  // Restart timer when task changes
  const taskId = task.id
  useEffect(() => {
    restartTimerRef.current()
    resetTaskState()
  }, [taskId]) // eslint-disable-line

  // Initial start
  useEffect(() => { restartTimerRef.current() }, []) // eslint-disable-line

  const selectFilter = (type) => {
    setFilterType(type)
    setCurrentIndex(0)
    resetTaskState()
  }

  const selectTask = (i) => {
    setCurrentIndex(i)
    resetTaskState()
  }

  const nextTask = () => {
    setCurrentIndex((currentIndex + 1) % filteredTasks.length)
    resetTaskState()
  }

  return (
    <Box>
      <Typography variant="h4" gutterBottom>Writing Practice</Typography>
      <Typography color="text.secondary" sx={{ mb: 3 }}>
        2026 format: 3 task types — Build a Sentence (2 min), Write an Email (7 min), Academic Discussion (10 min).
      </Typography>

      {/* Task type filter */}
      <Box sx={{ display: 'flex', gap: 1, mb: 3, flexWrap: 'wrap' }}>
        {taskTypes.map((type) => (
          <Button
            key={type}
            size="small"
            variant={filterType === type ? 'contained' : 'outlined'}
            color={filterType === type ? 'primary' : 'inherit'}
            onClick={() => selectFilter(type)}
          >
            {type === 'all' ? 'All Tasks' : type}
          </Button>
        ))}
      </Box>

      {/* Task navigation chips */}
      <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap', mb: 3 }}>
        {filteredTasks.map((t, i) => (
          <Chip
            key={t.id}
            label={i + 1}
            size="small"
            color={currentIndex === i ? 'primary' : completedIds.has(t.id) ? 'success' : 'default'}
            variant={currentIndex === i ? 'filled' : 'outlined'}
            onClick={() => selectTask(i)}
            sx={{ cursor: 'pointer' }}
          />
        ))}
      </Box>

      <SectionTimer label="Writing Task Timer" time={timer.formatted} percent={timer.percent} />

      <Card elevation={0} sx={{ borderRadius: 3, mb: 3 }}>
        <CardContent>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
            <Box>
              <Chip label={task.type} size="small" color={taskTypeColor(task.type)} variant="outlined" sx={{ mb: 0.5 }} />
              <Typography variant="caption" color="text.secondary" display="block">
                Task {currentIndex + 1} of {filteredTasks.length} · Timer: {formatTime(task.time)}
              </Typography>
            </Box>
            {task.type !== 'Build a Sentence' && (
              <Chip label={`${task.minWords}+ words`} size="small" variant="outlined" />
            )}
          </Box>

          {/* Build a Sentence */}
          {task.type === 'Build a Sentence' && (
            <Box sx={{ mb: 3 }}>
              <Typography fontWeight={500} sx={{ mb: 2 }}>
                Arrange the phrase chunks into the correct sentence:
              </Typography>

              <Typography variant="caption" color="text.secondary">Your arrangement:</Typography>
              <Box sx={{
                display: 'flex', gap: 1, flexWrap: 'wrap', p: 2, borderRadius: 2, mb: 2,
                minHeight: 52, border: '1px dashed', borderColor: 'primary.main',
                bgcolor: 'rgba(0,188,212,0.04)',
              }}>
                {arrangedChunks.map((chunk, ci) => (
                  <Chip
                    key={`arr-${ci}`}
                    label={chunk}
                    size="small"
                    color="primary"
                    onDelete={!submitted ? () => setArrangedChunks(arrangedChunks.filter((_, j) => j !== ci)) : undefined}
                    disabled={submitted}
                  />
                ))}
                {!arrangedChunks.length && (
                  <Typography variant="caption" color="text.secondary" sx={{ alignSelf: 'center' }}>
                    Click chunks below to build your sentence
                  </Typography>
                )}
              </Box>

              <Typography variant="caption" color="text.secondary">Available chunks:</Typography>
              <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mb: 2, mt: 0.5 }}>
                {availableChunks.map((chunk) => (
                  <Chip
                    key={chunk}
                    label={chunk}
                    size="small"
                    color="secondary"
                    variant="outlined"
                    disabled={submitted}
                    onClick={() => {
                      if (!arrangedChunks.includes(chunk)) setArrangedChunks([...arrangedChunks, chunk])
                    }}
                    sx={{ cursor: 'pointer' }}
                  />
                ))}
                {!availableChunks.length && !submitted && (
                  <Typography variant="caption" color="success.main">All chunks placed ✓</Typography>
                )}
              </Box>

              {submitted && (
                <Alert severity={chunkArrangementCorrect ? 'success' : 'error'} sx={{ mb: 2 }}>
                  {chunkArrangementCorrect
                    ? 'Correct! Well done.'
                    : `Not quite. The correct sentence is: ${task.correct}`}
                </Alert>
              )}
            </Box>
          )}

          {/* Write an Email */}
          {task.type === 'Write an Email' && (
            <Box sx={{ mb: 2 }}>
              <Box sx={{ mb: 2, p: 2, borderRadius: 2, borderLeft: '3px solid', borderColor: 'primary.main', bgcolor: 'action.hover' }}>
                <Typography variant="overline">Scenario</Typography>
                <Typography variant="body2" sx={{ mb: 1 }}>{task.scenario}</Typography>
                <Box sx={{ display: 'flex', gap: 1 }}>
                  <Chip label={`To: ${task.recipient}`} size="small" color="primary" variant="outlined" />
                  <Chip label={task.register} size="small" color="secondary" variant="outlined" />
                </Box>
              </Box>
              <Box sx={{ mb: 2, p: 2, borderRadius: 2, bgcolor: 'rgba(255,152,0,0.07)' }}>
                <Typography variant="caption" fontWeight={700} color="warning.main" display="block" sx={{ mb: 1 }}>
                  ✦ Your email MUST address all 3 of these points:
                </Typography>
                {task.bulletPoints?.map((point, i) => (
                  <Typography key={i} variant="body2" sx={{ mb: 0.5 }}>• {point}</Typography>
                ))}
              </Box>
              <Typography fontWeight={500} sx={{ mb: 2 }}>{task.prompt}</Typography>
              <TextField
                value={response}
                onChange={(e) => setResponse(e.target.value)}
                label="Write your email here"
                multiline
                rows={10}
                fullWidth
                disabled={submitting || submitted}
                sx={{ mb: 1 }}
              />
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
                <Typography variant="caption" color="text.secondary">
                  Word count: {words}
                  {words < (task.minWords || 0)
                    ? <span style={{ color: '#ff9800' }}> ({task.minWords - words} more needed)</span>
                    : <span style={{ color: '#4caf50' }}> ✓ Minimum met</span>}
                </Typography>
                <Typography variant="caption" color="text.secondary">Quality estimate: {quality}/5</Typography>
              </Box>
            </Box>
          )}

          {/* Academic Discussion */}
          {task.type === 'Academic Discussion' && (
            <Box sx={{ mb: 2 }}>
              <Typography fontWeight={500} sx={{ mb: 2, whiteSpace: 'pre-line' }}>{task.prompt}</Typography>
              {task.context && (
                <Box sx={{ mb: 2, p: 2, borderRadius: 2, borderLeft: '3px solid', borderColor: 'primary.main', bgcolor: 'action.hover' }}>
                  <Typography variant="caption"><strong>Discussion context:</strong> {task.context}</Typography>
                </Box>
              )}
              <TextField
                value={response}
                onChange={(e) => setResponse(e.target.value)}
                label="Write your discussion post"
                multiline
                rows={10}
                fullWidth
                disabled={submitting || submitted}
                sx={{ mb: 1 }}
              />
              <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
                <Typography variant="caption" color="text.secondary">
                  Word count: {words}
                  {words < (task.minWords || 0)
                    ? <span style={{ color: '#ff9800' }}> ({task.minWords - words} more needed)</span>
                    : <span style={{ color: '#4caf50' }}> ✓ Minimum met</span>}
                </Typography>
                <Typography variant="caption" color="text.secondary">Quality estimate: {quality}/5</Typography>
              </Box>
            </Box>
          )}

          {/* Sample response */}
          {submitted && task.sample && (
            <Box sx={{ mb: 2 }}>
              <Button size="small" variant="text" onClick={() => setShowSample(!showSample)}>
                {showSample ? 'Hide' : 'Show'} sample response
              </Button>
              {showSample && (
                <Alert severity="info" sx={{ mt: 1 }}>
                  <strong>Sample:</strong> {task.sample}
                </Alert>
              )}
            </Box>
          )}

          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
            <Button variant="contained" disabled={!canSubmit} onClick={submit}>
              {submitting ? 'Submitting…' : 'Submit Task'}
            </Button>
            <Button variant="outlined" disabled={submitting} onClick={nextTask}>
              Next Task →
            </Button>
          </Box>
        </CardContent>
      </Card>

      {submitted && task.type !== 'Build a Sentence' && (
        <Alert severity={words >= (task.minWords || 0) ? 'success' : 'warning'}>
          {words >= (task.minWords || 0)
            ? `Submitted! ${words} words — meets the minimum of ${task.minWords}.`
            : `Submitted with ${words} words. Aim for at least ${task.minWords} in the real exam.`}
        </Alert>
      )}

      <Snackbar
        open={toast}
        autoHideDuration={1800}
        onClose={() => setToast(false)}
        message="Task submitted and saved."
      />
    </Box>
  )
}

// src/views/practice/WritingPracticeView.vue
<template>
  <div>
    <h1 class="text-h4 mb-1">Writing Practice</h1>
    <p class="text-medium-emphasis mb-4">
      2026 format: 3 task types — Build a Sentence (2 min), Write an Email (7 min), Academic Discussion (10 min).
    </p>

    <!-- Task type filter tabs -->
    <div class="d-flex ga-2 mb-4 flex-wrap">
      <v-btn
        v-for="type in taskTypes"
        :key="type"
        :color="filterType === type ? 'primary' : 'default'"
        :variant="filterType === type ? 'flat' : 'tonal'"
        size="small"
        @click="selectFilter(type)"
      >
        {{ type === 'all' ? 'All Tasks' : type }}
      </v-btn>
    </div>

    <!-- Task navigation chips -->
    <div class="mb-4 d-flex ga-1 flex-wrap">
      <v-chip
        v-for="(t, idx) in filteredTasks"
        :key="t.id"
        :color="currentIndex === idx ? 'primary' : completedIds.has(t.id) ? 'success' : 'default'"
        :variant="currentIndex === idx ? 'flat' : 'tonal'"
        size="x-small"
        @click="selectTask(idx)"
      >
        {{ idx + 1 }}
      </v-chip>
    </div>

    <SectionTimer label="Writing Task Timer" :time="timer.formatted" :percent="timer.percent" />

    <v-card rounded="xl" elevation="0" class="pa-5 mb-4">
      <div class="d-flex justify-space-between align-center mb-3">
        <div>
          <v-chip
            size="small"
            :color="taskTypeColor(task.type)"
            variant="tonal"
            class="mb-1"
          >
            {{ task.type }}
          </v-chip>
          <div class="text-caption text-medium-emphasis">
            Task {{ currentIndex + 1 }} of {{ filteredTasks.length }}
            · Timer: {{ formatTime(task.time) }}
          </div>
        </div>
        <v-chip v-if="task.type !== 'Build a Sentence'" size="small" variant="outlined">{{ task.minWords }}+ words</v-chip>
      </div>

      <!-- ── Build a Sentence ─────────────────────────────────── -->
      <div v-if="task.type === 'Build a Sentence'" class="mb-4">
        <p class="font-weight-medium mb-3 text-body-1">
          Arrange the phrase chunks into the correct sentence:
        </p>

        <!-- Arranged chunks (user's current answer) -->
        <div class="text-caption text-medium-emphasis mb-1">Your arrangement:</div>
        <div
          class="d-flex ga-2 flex-wrap pa-3 rounded mb-3"
          style="min-height: 52px; background: rgba(var(--v-theme-primary), 0.06); border: 1px dashed rgba(var(--v-theme-primary), 0.3)"
        >
          <v-chip
            v-for="(chunk, ci) in arrangedChunks"
            :key="`arr-${ci}`"
            color="primary"
            variant="flat"
            size="small"
            :disabled="submitted"
            @click="removeChunk(ci)"
          >
            {{ chunk }}
            <v-icon v-if="!submitted" size="x-small" class="ml-1">mdi-close</v-icon>
          </v-chip>
          <span
            v-if="!arrangedChunks.length"
            class="text-caption text-medium-emphasis align-self-center"
          >Click chunks below to build your sentence</span>
        </div>

        <!-- Available chunks to click -->
        <div class="text-caption text-medium-emphasis mb-2">Available chunks:</div>
        <div class="d-flex ga-2 flex-wrap mb-3">
          <v-chip
            v-for="chunk in availableChunks"
            :key="chunk"
            color="secondary"
            variant="tonal"
            size="small"
            :disabled="submitted"
            style="cursor: pointer"
            @click="addChunk(chunk)"
          >
            {{ chunk }}
          </v-chip>
          <span v-if="!availableChunks.length && !submitted" class="text-caption text-success">
            All chunks placed ✓
          </span>
        </div>

        <!-- Correctness hint after submit -->
        <v-alert
          v-if="submitted"
          :type="chunkArrangementCorrect ? 'success' : 'error'"
          variant="tonal"
          density="compact"
          class="mb-3"
        >
          <span v-if="chunkArrangementCorrect">Correct! Well done.</span>
          <span v-else>
            Not quite. The correct sentence is:
            <strong>{{ task.correct }}</strong>
          </span>
        </v-alert>
      </div>

      <!-- ── Write an Email ────────────────────────────────────── -->
      <div v-else-if="task.type === 'Write an Email'" class="mb-3">
        <div
          class="mb-3 pa-3 rounded"
          style="background: rgba(0,0,0,0.04); border-left: 3px solid rgba(var(--v-theme-primary), 0.5)"
        >
          <div class="text-overline mb-1">Scenario</div>
          <p class="text-body-2 mb-2">{{ task.scenario }}</p>
          <div class="d-flex ga-3 flex-wrap">
            <v-chip size="x-small" variant="tonal" color="primary">To: {{ task.recipient }}</v-chip>
            <v-chip size="x-small" variant="tonal" color="secondary">{{ task.register }}</v-chip>
          </div>
        </div>

        <!-- 3 mandatory bullet points -->
        <div class="mb-3 pa-3 rounded" style="background: rgba(var(--v-theme-warning), 0.07)">
          <div class="text-caption font-weight-bold text-warning mb-2">
            ✦ Your email MUST address all 3 of these points:
          </div>
          <div
            v-for="(point, i) in task.bulletPoints"
            :key="i"
            class="d-flex ga-2 align-start mb-1"
          >
            <v-icon size="x-small" color="warning" class="mt-1">mdi-circle-medium</v-icon>
            <span class="text-body-2">{{ point }}</span>
          </div>
        </div>

        <p class="font-weight-medium mb-3 text-body-1">{{ task.prompt }}</p>

        <v-textarea
          v-model="response"
          label="Write your email here"
          rows="10"
          auto-grow
          variant="outlined"
          :disabled="submitting || submitted"
          class="mb-1"
        />
        <div class="d-flex justify-space-between align-center mb-3">
          <div class="text-caption text-medium-emphasis">
            Word count: {{ words }}
            <span v-if="words < task.minWords" class="text-warning">
              ({{ task.minWords - words }} more needed)
            </span>
            <span v-else class="text-success">✓ Minimum met</span>
          </div>
          <div class="text-caption text-medium-emphasis">Quality estimate: {{ quality }}/5</div>
        </div>
      </div>

      <!-- ── Academic Discussion ──────────────────────────────── -->
      <div v-else class="mb-3">
        <p class="font-weight-medium mb-3 text-body-1" style="white-space: pre-line">{{ task.prompt }}</p>

        <div
          v-if="task.context"
          class="mb-3 pa-3 rounded text-caption text-medium-emphasis"
          style="background: rgba(0,0,0,0.04); border-left: 3px solid rgba(var(--v-theme-primary),0.4)"
        >
          <strong>Discussion context:</strong> {{ task.context }}
        </div>

        <v-textarea
          v-model="response"
          label="Write your discussion post"
          rows="10"
          auto-grow
          variant="outlined"
          :disabled="submitting || submitted"
          class="mb-1"
        />
        <div class="d-flex justify-space-between align-center mb-3">
          <div class="text-caption text-medium-emphasis">
            Word count: {{ words }}
            <span v-if="words < task.minWords" class="text-warning">
              ({{ task.minWords - words }} more needed)
            </span>
            <span v-else class="text-success">✓ Minimum met</span>
          </div>
          <div class="text-caption text-medium-emphasis">Quality estimate: {{ quality }}/5</div>
        </div>
      </div>

      <!-- Sample response toggle (only after submit) -->
      <div v-if="submitted && task.sample" class="mb-3">
        <v-btn size="x-small" variant="text" @click="showSample = !showSample">
          {{ showSample ? 'Hide' : 'Show' }} sample response
        </v-btn>
        <v-alert v-if="showSample" type="info" variant="tonal" density="compact" class="mt-2 text-body-2">
          <strong>Sample:</strong> {{ task.sample }}
        </v-alert>
      </div>

      <div class="d-flex ga-2 flex-wrap">
        <v-btn
          color="primary"
          :loading="submitting"
          :disabled="!canSubmit"
          @click="submit"
        >
          Submit Task
        </v-btn>
        <v-btn variant="tonal" :disabled="submitting" @click="nextTask">Next Task →</v-btn>
      </div>
    </v-card>

    <transition name="page-fade">
      <v-alert
        v-if="submitted && task.type !== 'Build a Sentence'"
        :type="words >= task.minWords ? 'success' : 'warning'"
        variant="tonal"
        density="compact"
      >
        {{ words >= task.minWords
          ? `Submitted! ${words} words — meets the minimum of ${task.minWords}.`
          : `Submitted with ${words} words. Aim for at least ${task.minWords} in the real exam.` }}
      </v-alert>
    </transition>

    <v-snackbar v-model="toast" timeout="1800" color="success">Task submitted and saved.</v-snackbar>
  </div>
</template>

<script setup>
import { computed, ref, watch } from 'vue'
import { writingTasks } from '../../data/writing'
import { useTimer } from '../../composables/useTimer'
import SectionTimer from '../../components/SectionTimer.vue'
import { useProgressStore } from '../../stores/progress'

const progress = useProgressStore()

const filterType = ref('all')
const taskTypes = ['all', 'Build a Sentence', 'Write an Email', 'Academic Discussion']

const filteredTasks = computed(() => {
  if (filterType.value === 'all') return writingTasks
  return writingTasks.filter((t) => t.type === filterType.value)
})

const currentIndex = ref(0)
const response = ref('')
const submitted = ref(false)
const submitting = ref(false)
const toast = ref(false)
const showSample = ref(false)
const completedIds = ref(new Set())

// ── Build a Sentence chunk state ──────────────────────────────────
const arrangedChunks = ref([])

const task = computed(() => filteredTasks.value[currentIndex.value] || writingTasks[0])

// Shuffle chunks deterministically by task id so order is scrambled but reproducible
const shuffledChunks = computed(() => {
  if (task.value.type !== 'Build a Sentence' || !task.value.chunks) return []
  const seed = task.value.id.charCodeAt(task.value.id.length - 1)
  return [...task.value.chunks].sort(
    (a, b) => (a.charCodeAt(0) * seed + a.length) % 11 - (b.charCodeAt(0) * seed + b.length) % 11
  )
})

const availableChunks = computed(() =>
  shuffledChunks.value.filter((c) => !arrangedChunks.value.includes(c))
)

const chunkArrangementCorrect = computed(() => {
  if (task.value.type !== 'Build a Sentence' || !task.value.chunks) return false
  return arrangedChunks.value.join(' ') === task.value.chunks.join(' ')
})

const addChunk = (chunk) => {
  if (!arrangedChunks.value.includes(chunk)) arrangedChunks.value.push(chunk)
}

const removeChunk = (i) => {
  arrangedChunks.value.splice(i, 1)
}

// ── Shared computed ───────────────────────────────────────────────
const words = computed(() =>
  response.value.trim() ? response.value.trim().split(/\s+/).length : 0
)

const quality = computed(() => {
  const lengthScore = Math.max(1, Math.min(5, Math.round((words.value / (task.value.minWords || 80)) * 5)))
  const sentenceCount = response.value.split(/[.!?]+/).filter(Boolean).length
  const structureScore = Math.max(1, Math.min(5, sentenceCount >= 4 ? 5 : sentenceCount + 1))
  return Math.round((lengthScore + structureScore) / 2)
})

const canSubmit = computed(() => {
  if (submitting.value || submitted.value) return false
  if (task.value.type === 'Build a Sentence') {
    return (
      task.value.chunks &&
      arrangedChunks.value.length === task.value.chunks.length
    )
  }
  return response.value.trim().length > 0
})

const formatTime = (sec) => {
  const m = Math.floor(sec / 60)
  const s = sec % 60
  return s === 0 ? `${m} min` : `${m}:${String(s).padStart(2, '0')}`
}

const taskTypeColor = (type) => {
  if (type === 'Build a Sentence') return 'success'
  if (type === 'Write an Email') return 'primary'
  return 'secondary'
}

const timer = useTimer(task.value.time)

const restartTimer = () => {
  timer.reset(task.value.time)
  timer.start(() => {
    if (!submitted.value) submit()
  })
}

const resetTaskState = () => {
  response.value = ''
  arrangedChunks.value = []
  submitted.value = false
  submitting.value = false
  showSample.value = false
}

watch(task, () => {
  restartTimer()
  resetTaskState()
})

restartTimer()

const selectFilter = (type) => {
  filterType.value = type
  currentIndex.value = 0
  resetTaskState()
}

const selectTask = (idx) => {
  currentIndex.value = idx
  resetTaskState()
}

const submit = async () => {
  if (!canSubmit.value) return
  submitting.value = true

  // For Build a Sentence, mirror arrangement into response for record-keeping
  if (task.value.type === 'Build a Sentence') {
    response.value = arrangedChunks.value.join(' ')
  }

  await new Promise((r) => setTimeout(r, 200))
  submitted.value = true
  submitting.value = false
  toast.value = true
  completedIds.value.add(task.value.id)
  progress.addWriting()
}

const nextTask = () => {
  currentIndex.value = (currentIndex.value + 1) % filteredTasks.value.length
  resetTaskState()
}
</script>
