// src/views/AnalyticsView.vue
<template>
  <div>
    <h1 class="text-h4 mb-2">Analytics</h1>
    <p class="text-medium-emphasis mb-6">Section-level progress from your local attempts.</p>

    <v-row>
      <v-col cols="12" md="6">
        <v-card rounded="xl" elevation="0" class="pa-4">
          <div class="text-overline">Reading Scores</div>
          <div class="text-h6">{{ readingText }}</div>
        </v-card>
      </v-col>
      <v-col cols="12" md="6">
        <v-card rounded="xl" elevation="0" class="pa-4">
          <div class="text-overline">Listening Scores</div>
          <div class="text-h6">{{ listeningText }}</div>
        </v-card>
      </v-col>
      <v-col cols="12" md="6">
        <v-card rounded="xl" elevation="0" class="pa-4">
          <div class="text-overline">Writing Submissions</div>
          <div class="text-h6">{{ s.writingSubmissions }}</div>
        </v-card>
      </v-col>
      <v-col cols="12" md="6">
        <v-card rounded="xl" elevation="0" class="pa-4">
          <div class="text-overline">Speaking Attempts</div>
          <div class="text-h6">{{ s.speakingAttempts }}</div>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useProgressStore } from '../stores/progress'

const s = useProgressStore()

const readingText = computed(() => s.readingScores.length ? s.readingScores.join(', ') : 'No attempts yet')
const listeningText = computed(() => s.listeningScores.length ? s.listeningScores.join(', ') : 'No attempts yet')
</script>

// src/views/AnalyticsView.jsx
import React from 'react'
import { Box, Card, CardContent, Grid, Typography } from '@mui/material'
import { useProgressStore } from '../store/useProgressStore'

export default function AnalyticsView() {
  const s = useProgressStore()
  const stats = [
    { label: 'Reading Scores', value: s.readingScores.length ? s.readingScores.map((v) => `${v}%`).join(', ') : 'No attempts yet' },
    { label: 'Listening Scores', value: s.listeningScores.length ? s.listeningScores.map((v) => `${v}%`).join(', ') : 'No attempts yet' },
    { label: 'Writing Submissions', value: String(s.writingSubmissions) },
    { label: 'Speaking Attempts', value: String(s.speakingAttempts) },
  ]
  return (
    <Box>
      <Typography variant="h4" gutterBottom>Analytics</Typography>
      <Typography color="text.secondary" sx={{ mb: 4 }}>
        Section-level progress from your local attempts.
      </Typography>
      <Grid container spacing={2}>
        {stats.map((st) => (
          <Grid item xs={12} md={6} key={st.label}>
            <Card elevation={0} sx={{ borderRadius: 3 }}>
              <CardContent>
                <Typography variant="overline" color="text.secondary">{st.label}</Typography>
                <Typography variant="h6">{st.value}</Typography>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Box>
  )
}
