// src/views/DashboardView.vue
<template>
  <div>
    <h1 class="text-h4 mb-1">Welcome back</h1>
    <p class="text-medium-emphasis mb-5">Your TOEFL 2026 preparation dashboard.</p>

    <!-- KPI cards -->
    <v-row class="mb-4">
      <v-col cols="6" sm="4" md="2" v-for="card in cards" :key="card.title">
        <v-card rounded="xl" elevation="0" class="pa-4">
          <div class="text-caption text-medium-emphasis mb-1">{{ card.title }}</div>
          <div class="text-h5 font-weight-bold">{{ card.value }}</div>
        </v-card>
      </v-col>
    </v-row>

    <!-- Format overview -->
    <v-card rounded="xl" elevation="0" class="pa-5 mb-4">
      <div class="text-h6 mb-3">2026 TOEFL Format Overview</div>
      <v-row dense>
        <v-col cols="12" sm="6" md="3" v-for="section in formatSections" :key="section.name">
          <div class="pa-3 rounded mb-2" style="background: rgba(0,0,0,0.04)">
            <div class="text-overline" :style="{ color: section.color }">{{ section.name }}</div>
            <div class="text-body-2 font-weight-medium mb-1">{{ section.tasks }}</div>
            <div class="text-caption text-medium-emphasis">{{ section.detail }}</div>
          </div>
        </v-col>
      </v-row>
      <div class="text-caption text-medium-emphasis mt-2">
        Total test time: ~67–85 min · Score: 1–6 banded scale (CEFR-aligned)
      </div>
    </v-card>

    <!-- Quick actions -->
    <v-card rounded="xl" elevation="0" class="pa-4">
      <div class="text-h6 mb-3">Quick Actions</div>
      <div class="d-flex ga-2 flex-wrap">
        <v-btn color="primary" :to="'/practice'">Practice Sections</v-btn>
        <v-btn color="secondary" :to="'/exam'">Take a Mock Exam</v-btn>
        <v-btn variant="tonal" :to="'/analytics'">View Analytics</v-btn>
      </div>
    </v-card>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useProgressStore } from '../stores/progress'
import { useBandEstimate } from '../composables/useBandEstimate'

const s = useProgressStore()

const overallPercent = computed(() => {
  const vals = [s.avgReading, s.avgListening].filter((x) => x > 0)
  return vals.length ? Math.round(vals.reduce((a, b) => a + b, 0) / vals.length) : 0
})

const cards = computed(() => [
  { title: 'Practice Sessions', value: String(s.practiceSessions) },
  { title: 'Mock Exams Taken', value: String(s.mockExamsTaken) },
  { title: 'Reading Avg', value: s.avgReading ? `${s.avgReading}%` : '—' },
  { title: 'Listening Avg', value: s.avgListening ? `${s.avgListening}%` : '—' },
  { title: 'Writing Done', value: String(s.writingSubmissions) },
  {
    title: 'Est. Band (1–6)',
    value: overallPercent.value ? String(useBandEstimate(overallPercent.value)) : '—',
  },
])

const formatSections = [
  {
    name: 'Reading',
    color: 'rgb(var(--v-theme-primary))',
    tasks: 'Adaptive · 2 stages',
    detail: 'Complete the Words · Read in Daily Life · Academic Passage',
  },
  {
    name: 'Listening',
    color: 'rgb(var(--v-theme-secondary))',
    tasks: 'Adaptive · 2 stages',
    detail: 'Choose a Response · Conversation · Announcement · Academic Talk',
  },
  {
    name: 'Writing',
    color: '#4CAF50',
    tasks: '3 task types',
    detail: 'Build a Sentence · Write an Email · Academic Discussion',
  },
  {
    name: 'Speaking',
    color: '#FF9800',
    tasks: '11 tasks total',
    detail: '7 Listen & Repeat (8–12s) · 4 Take an Interview (45s each)',
  },
]
</script>

// src/views/DashboardView.jsx
import React from 'react'
import { useNavigate } from 'react-router-dom'
import { Box, Button, Card, CardContent, Grid, Typography } from '@mui/material'
import { useProgressStore } from '../store/useProgressStore'
import { getBandEstimate } from '../hooks/useBandEstimate'

const formatSections = [
  {
    name: 'Reading',
    color: '#00BCD4',
    tasks: 'Adaptive · 2 stages',
    detail: 'Complete the Words · Read in Daily Life · Academic Passage',
  },
  {
    name: 'Listening',
    color: '#7C4DFF',
    tasks: 'Adaptive · 2 stages',
    detail: 'Choose a Response · Conversation · Announcement · Academic Talk',
  },
  {
    name: 'Writing',
    color: '#4CAF50',
    tasks: '3 task types',
    detail: 'Build a Sentence · Write an Email · Academic Discussion',
  },
  {
    name: 'Speaking',
    color: '#FF9800',
    tasks: '11 tasks total',
    detail: '7 Listen & Repeat (8–12s) · 4 Take an Interview (45s each)',
  },
]

const avg = (arr) => (arr.length ? Math.round(arr.reduce((a, b) => a + b, 0) / arr.length) : 0)

export default function DashboardView() {
  const navigate = useNavigate()
  const s = useProgressStore()
  const avgReading = avg(s.readingScores)
  const avgListening = avg(s.listeningScores)
  const vals = [avgReading, avgListening].filter((x) => x > 0)
  const overallPct = vals.length ? Math.round(vals.reduce((a, b) => a + b, 0) / vals.length) : 0

  const cards = [
    { title: 'Practice Sessions', value: String(s.practiceSessions) },
    { title: 'Mock Exams Taken', value: String(s.mockExamsTaken) },
    { title: 'Reading Avg', value: avgReading ? `${avgReading}%` : '—' },
    { title: 'Listening Avg', value: avgListening ? `${avgListening}%` : '—' },
    { title: 'Writing Done', value: String(s.writingSubmissions) },
    { title: 'Est. Band (1–6)', value: overallPct ? String(getBandEstimate(overallPct)) : '—' },
  ]

  return (
    <Box>
      <Typography variant="h4" gutterBottom>Welcome back</Typography>
      <Typography color="text.secondary" sx={{ mb: 3 }}>Your TOEFL 2026 preparation dashboard.</Typography>

      <Grid container spacing={2} sx={{ mb: 3 }}>
        {cards.map((c) => (
          <Grid item xs={6} sm={4} md={2} key={c.title}>
            <Card elevation={0} sx={{ borderRadius: 3 }}>
              <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                <Typography variant="caption" color="text.secondary" display="block">{c.title}</Typography>
                <Typography variant="h5" fontWeight={700}>{c.value}</Typography>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>

      <Card elevation={0} sx={{ borderRadius: 3, p: 1, mb: 3 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>2026 TOEFL Format Overview</Typography>
          <Grid container spacing={2}>
            {formatSections.map((sec) => (
              <Grid item xs={12} sm={6} md={3} key={sec.name}>
                <Box sx={{ p: 2, borderRadius: 2, bgcolor: 'action.hover' }}>
                  <Typography variant="overline" style={{ color: sec.color }}>{sec.name}</Typography>
                  <Typography variant="body2" fontWeight={500}>{sec.tasks}</Typography>
                  <Typography variant="caption" color="text.secondary">{sec.detail}</Typography>
                </Box>
              </Grid>
            ))}
          </Grid>
          <Typography variant="caption" color="text.secondary" sx={{ mt: 2, display: 'block' }}>
            Total test time: ~67–85 min · Score: 1–6 banded scale (CEFR-aligned)
          </Typography>
        </CardContent>
      </Card>

      <Card elevation={0} sx={{ borderRadius: 3, p: 1 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>Quick Actions</Typography>
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
            <Button variant="contained" color="primary" onClick={() => navigate('/practice')}>
              Practice Sections
            </Button>
            <Button variant="contained" color="secondary" onClick={() => navigate('/exam')}>
              Take a Mock Exam
            </Button>
            <Button variant="outlined" onClick={() => navigate('/analytics')}>
              View Analytics
            </Button>
          </Box>
        </CardContent>
      </Card>
    </Box>
  )
}
