// src/views/SettingsView.vue
<template>
  <div>
    <h1 class="text-h4 mb-2">Settings</h1>
    <p class="text-medium-emphasis mb-6">Audio/microphone permissions, exam preferences, and progress data management.</p>

    <v-card rounded="xl" elevation="0" class="pa-4 mb-4">
      <div class="text-h6 mb-2">Permission Manager</div>
      <div class="mb-3">Microphone permission state: <strong>{{ micState }}</strong></div>
      <div class="d-flex ga-2 flex-wrap">
        <v-btn color="primary" :loading="checkingPerm" @click="probePermission">Refresh Permission</v-btn>
        <v-btn variant="tonal" :loading="requestingMic" @click="requestMic">Request Microphone Access</v-btn>
      </div>
      <div class="text-caption mt-3 text-medium-emphasis">If denied, re-enable mic in browser site settings.</div>
    </v-card>

    <v-card rounded="xl" elevation="0" class="pa-4 mb-4">
      <div class="text-h6 mb-2">Progress Backup</div>
      <div class="d-flex ga-2 flex-wrap">
        <v-btn color="secondary" @click="exportProgress">Export Progress JSON</v-btn>
        <v-btn variant="tonal" @click="triggerImport">Import Progress JSON</v-btn>
        <input ref="fileInput" type="file" accept="application/json" class="d-none" @change="onImportFile" />
      </div>
      <div class="text-caption mt-3 text-medium-emphasis">Import overwrites current local progress.</div>
    </v-card>

    <v-card rounded="xl" elevation="0" class="pa-4">
      <div class="text-h6 mb-2">Danger Zone</div>
      <v-btn color="error" variant="tonal" @click="confirmReset = true">Reset All Progress</v-btn>
    </v-card>

    <v-dialog v-model="confirmReset" max-width="420">
      <v-card>
        <v-card-title>Reset all progress?</v-card-title>
        <v-card-text>This will permanently delete local scores and attempt history.</v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="confirmReset = false">Cancel</v-btn>
          <v-btn color="error" @click="resetProgress">Reset</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-snackbar v-model="toast" timeout="1800" color="success">{{ toastText }}</v-snackbar>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useProgressStore } from '../stores/progress'

const store = useProgressStore()
const micState = ref('unknown')
const fileInput = ref(null)
const checkingPerm = ref(false)
const requestingMic = ref(false)
const confirmReset = ref(false)
const toast = ref(false)
const toastText = ref('')

const showToast = (text) => {
  toastText.value = text
  toast.value = true
}

const probePermission = async () => {
  checkingPerm.value = true
  try {
    if (!navigator.permissions) {
      micState.value = 'unavailable-api'
      return
    }
    const p = await navigator.permissions.query({ name: 'microphone' })
    micState.value = p.state
  } catch {
    micState.value = 'unknown'
  } finally {
    checkingPerm.value = false
  }
}

const requestMic = async () => {
  requestingMic.value = true
  try {
    const s = await navigator.mediaDevices.getUserMedia({ audio: true })
    micState.value = 'granted'
    s.getTracks().forEach((t) => t.stop())
    showToast('Microphone access granted.')
  } catch {
    micState.value = 'denied'
    showToast('Microphone access denied.')
  } finally {
    requestingMic.value = false
  }
}

const exportProgress = () => {
  const blob = new Blob([store.exportJson()], { type: 'application/json' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `toefl-progress-${Date.now()}.json`
  a.click()
  URL.revokeObjectURL(a.href)
  showToast('Progress exported.')
}

const triggerImport = () => {
  fileInput.value?.click()
}

const onImportFile = async (e) => {
  const file = e.target.files?.[0]
  if (!file) return
  const text = await file.text()
  try {
    store.importJson(text)
    showToast('Progress imported successfully.')
  } catch {
    showToast('Invalid JSON file.')
  }
  e.target.value = ''
}

const resetProgress = () => {
  store.resetAll()
  confirmReset.value = false
  showToast('Progress reset.')
}

onMounted(probePermission)
</script>

// src/views/SettingsView.jsx
import React, { useEffect, useRef, useState } from 'react'
import {
  Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent,
  DialogTitle, Snackbar, Typography,
} from '@mui/material'
import { useProgressStore } from '../store/useProgressStore'

export default function SettingsView() {
  const store = useProgressStore()
  const [micState, setMicState] = useState('unknown')
  const [checkingPerm, setCheckingPerm] = useState(false)
  const [requestingMic, setRequestingMic] = useState(false)
  const [confirmReset, setConfirmReset] = useState(false)
  const [toast, setToast] = useState({ open: false, message: '' })
  const fileInputRef = useRef(null)

  const showToast = (msg) => setToast({ open: true, message: msg })

  const probePermission = async () => {
    setCheckingPerm(true)
    try {
      if (!navigator.permissions) { setMicState('unavailable-api'); return }
      const p = await navigator.permissions.query({ name: 'microphone' })
      setMicState(p.state)
    } catch { setMicState('unknown') }
    finally { setCheckingPerm(false) }
  }

  const requestMic = async () => {
    setRequestingMic(true)
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
      setMicState('granted')
      stream.getTracks().forEach((t) => t.stop())
      showToast('Microphone access granted.')
    } catch {
      setMicState('denied')
      showToast('Microphone access denied.')
    } finally { setRequestingMic(false) }
  }

  const exportProgress = () => {
    const blob = new Blob([store.exportJson()], { type: 'application/json' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `toefl-progress-${Date.now()}.json`
    a.click()
    URL.revokeObjectURL(a.href)
    showToast('Progress exported.')
  }

  const onImportFile = async (e) => {
    const file = e.target.files?.[0]
    if (!file) return
    const text = await file.text()
    try {
      store.importJson(text)
      showToast('Progress imported successfully.')
    } catch { showToast('Invalid JSON file.') }
    e.target.value = ''
  }

  const resetProgress = () => {
    store.resetAll()
    setConfirmReset(false)
    showToast('Progress reset.')
  }

  useEffect(() => { probePermission() }, [])

  return (
    <Box>
      <Typography variant="h4" gutterBottom>Settings</Typography>
      <Typography color="text.secondary" sx={{ mb: 4 }}>
        Audio/microphone permissions, exam preferences, and progress data management.
      </Typography>

      <Card elevation={0} sx={{ borderRadius: 3, mb: 2 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>Permission Manager</Typography>
          <Typography sx={{ mb: 2 }}>
            Microphone permission state: <strong>{micState}</strong>
          </Typography>
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
            <Button variant="contained" disabled={checkingPerm} onClick={probePermission}>
              {checkingPerm ? 'Checking…' : 'Refresh Permission'}
            </Button>
            <Button variant="outlined" disabled={requestingMic} onClick={requestMic}>
              {requestingMic ? 'Requesting…' : 'Request Microphone Access'}
            </Button>
          </Box>
          <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
            If denied, re-enable mic in browser site settings.
          </Typography>
        </CardContent>
      </Card>

      <Card elevation={0} sx={{ borderRadius: 3, mb: 2 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>Progress Backup</Typography>
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
            <Button variant="contained" color="secondary" onClick={exportProgress}>
              Export Progress JSON
            </Button>
            <Button variant="outlined" onClick={() => fileInputRef.current?.click()}>
              Import Progress JSON
            </Button>
            <input
              ref={fileInputRef}
              type="file"
              accept="application/json"
              style={{ display: 'none' }}
              onChange={onImportFile}
            />
          </Box>
          <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
            Import overwrites current local progress.
          </Typography>
        </CardContent>
      </Card>

      <Card elevation={0} sx={{ borderRadius: 3 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>Danger Zone</Typography>
          <Button variant="outlined" color="error" onClick={() => setConfirmReset(true)}>
            Reset All Progress
          </Button>
        </CardContent>
      </Card>

      <Dialog open={confirmReset} onClose={() => setConfirmReset(false)} maxWidth="xs" fullWidth>
        <DialogTitle>Reset all progress?</DialogTitle>
        <DialogContent>
          <Typography>This will permanently delete local scores and attempt history.</Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setConfirmReset(false)}>Cancel</Button>
          <Button color="error" onClick={resetProgress}>Reset</Button>
        </DialogActions>
      </Dialog>

      <Snackbar
        open={toast.open}
        autoHideDuration={1800}
        onClose={() => setToast((t) => ({ ...t, open: false }))}
        message={toast.message}
      />
    </Box>
  )
}
