// src/components/SectionTimer.jsx
import React from 'react'
import { Box, LinearProgress, Paper, Typography } from '@mui/material'

export default function SectionTimer({ label = 'Time Remaining', time, percent }) {
  return (
    <Paper elevation={0} sx={{ p: 2, mb: 2, borderRadius: 3 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
        <Typography variant="body2" fontWeight={500}>{label}</Typography>
        <Typography variant="h6">{time}</Typography>
      </Box>
      <LinearProgress
        variant="determinate"
        value={percent}
        sx={{ height: 10, borderRadius: 5 }}
      />
    </Paper>
  )
}

// src/components/SectionTimer.vue
<template>
  <v-card rounded="xl" elevation="0" class="pa-4 mb-4">
    <div class="d-flex align-center justify-space-between mb-2">
      <div class="text-subtitle-2">{{ label }}</div>
      <div class="text-h6">{{ time }}</div>
    </div>
    <v-progress-linear :model-value="percent" color="primary" height="10" rounded />
  </v-card>
</template>

<script setup>
defineProps({
  label: { type: String, default: 'Time Remaining' },
  time: { type: String, required: true },
  percent: { type: Number, required: true },
})
</script>
